# general
device: 'cuda'

# data
input_video: 'input/sample2.mp4'
output_path: 'output'
ddim_latents_path: 'initial_latents'
w: 512
h: 512

# diffusion
guidance_scale: 7.5
n_timesteps: 50
source_prompt: "A man wears a green shirt"
target_prompt: "A man wears a yellow shirt"
negative_prompt: "ugly, blurry, low res, unrealistic, unaesthetic"

# quality enhancemet module: propagation, attention
module: 'propagation'
#module: 'causal_attention'
#module: 'basic_attention'

# frag
min_size: 1 # high min_size -- fast edit, low quality, attention: 5 > min_size
scheduler_beta: 3.00 
# leverage scheduler, (optional, 0<beta<5) high => start with large groups for low frequency
# too high value can lose highfrequency details

# pnp params -- injection thresholds [0, 1]
pnp_attn_t: 0.5
pnp_f_t: 0.8
